id: P003167
initial_creation_type: ocr
source_metadata:
  id: bdr:W00KG09759
  title: རྟ་ཝང་དགའ་ལྡན་རྣམ་རྒྱལ་ལྷ་རྩེའི་བཅའ་ཡིག་མདོར་བསྡུས་
  author: ''
  volumes:
    6160871a55804de9980fb1648b986a35:
      image_group_id: I00KG09841
      title: ''
      volume_number: 1
      total_pages: 54
