id: IB999E0A5
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-28T20:54:00+00:00'
last_modified: '2022-06-07T18:02:28.608406+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W00KG09759
  title: རྟ་ཝང་དགའ་ལྡན་རྣམ་རྒྱལ་ལྷ་རྩེའི་བཅའ་ཡིག་མདོར་བསྡུས་
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    69C7:
      image_group_id: I00KG09841
      title: ''
      total_pages: 54
      order: 1
      base_file: 69C7.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
